# Generated by Django 2.2.1 on 2019-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20190523_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
