# Generated by Django 2.2.1 on 2019-05-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20190523_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('description', models.TextField(max_length=1024)),
                ('address', models.TextField(max_length=200)),
                ('phone', models.TextField(max_length=200)),
                ('siteurl', models.URLField()),
                ('rating', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_cateogry', to='guide.Category')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
    ]
