# Generated by Django 2.2.1 on 2019-05-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
