# Generated by Django 2.2.1 on 2019-05-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_auto_20190524_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(default=2, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='place',
            name='siteurl',
            field=models.URLField(blank=True),
        ),
    ]
